// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3OIqeVZPgH1_o7ME6a_lo4-jqVXNOP0',
    appId: '1:685571696877:web:3cdc0fe5ec719accb584e4',
    messagingSenderId: '685571696877',
    projectId: 'stegn-6aed8',
    authDomain: 'stegn-6aed8.firebaseapp.com',
    storageBucket: 'stegn-6aed8.firebasestorage.app',
    measurementId: 'G-FTP33NE8S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_v81oCZl2d8eqLb3jKdCv1EDer5XDhU',
    appId: '1:685571696877:android:09fa593c0be2a7fbb584e4',
    messagingSenderId: '685571696877',
    projectId: 'stegn-6aed8',
    storageBucket: 'stegn-6aed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgKw1IXjOZ_fxQD7-9WgPXai-dsKnbjw',
    appId: '1:685571696877:ios:6b309d556bc99de2b584e4',
    messagingSenderId: '685571696877',
    projectId: 'stegn-6aed8',
    storageBucket: 'stegn-6aed8.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgKw1IXjOZ_fxQD7-9WgPXai-dsKnbjw',
    appId: '1:685571696877:ios:6b309d556bc99de2b584e4',
    messagingSenderId: '685571696877',
    projectId: 'stegn-6aed8',
    storageBucket: 'stegn-6aed8.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3OIqeVZPgH1_o7ME6a_lo4-jqVXNOP0',
    appId: '1:685571696877:web:0420d2162f303be7b584e4',
    messagingSenderId: '685571696877',
    projectId: 'stegn-6aed8',
    authDomain: 'stegn-6aed8.firebaseapp.com',
    storageBucket: 'stegn-6aed8.firebasestorage.app',
    measurementId: 'G-PB450GG5ZY',
  );
}
